### ISSUE TITLE
安装了VSCode但是它却没有检测到VScode - Bug

### ISSUE THREAD

**Issue by laolizhennui** [d2learn/xlings#25]
安装了VSCode但是它却没有检测到VScode，并且我添加了环境变量！
![屏幕截图 2024-11-15 193706](https://github.com/user-attachments/assets/48d3ce24-69db-40f7-b535-0dd372f07570)

**Comment by Sunrisepeak** [comment]
直接在命令行运行 code --version 能看到安装的具体版本吗

**Comment by Sunrisepeak** [comment]
我看你的命令行窗口是admin的powershell, 可能是之前安装的vscode的窗口分了系统环境变量和当前用户环境变量。你用普通运行cmd命令窗口中看看能不能用code命令直接启动 以及 使用 xlings install vscode 看看会不会提示已经安装 同一个命令行环境下, 如果直接运行code可以识别到vscode, 按理xlings应该也是可以检测到的

**Comment by laolizhennui** [comment]
> 直接在命令行运行 code --version 能看到安装的具体版本吗

可以
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64

**Comment by laolizhennui** [comment]
> 我看你的命令行窗口是admin的powershell， 可能是之前安装的vscode的窗口分了系统环境变量和当前用户环境变量。你用普通运行cmd命令窗口中看看能不能用code命令直接启动 以及 使用 xlings install vscode 看看会不会提示已经安装 同一个命令行环境下， 如果直接运行code命令可以识别到vscode， 按理xlings应该也是可以检测到的
> 
> ![图像](https://private-user-images.githubusercontent.com/38786181/386672744-b2b53b9b-5c65-400e-9290-098ff9f5f5bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MzkxOTYsIm5iZiI6MTczMTczODg5NiwicGF0aCI6Ii8zODc4NjE4MS8zODY2NzI3NDQtYjJiNTNiOWItNWM2NS00MDBlLTkyOTAtMDk4ZmY5ZjVmNWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OWI2NTM5YWRlZDY3NzAxZTk1NTM0ZGYwNzdlMDMzOTA2M2EzNGVjY2E2MmU4MzFhMTM2M2E1M2ZiNDM3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0fBHNCSNYxBTFzCIBTXrOlD3r_mK7tu0M_jnbqhuBu4)

可以运行code，我装不是win64user版的，是win64版的

**Comment by Sunrisepeak** [comment]
使用 `xlings install vscode` 能显示已经被安装吗?  还是提示重新安装, 可以在powershell 和 cmd 上都试一下 看看情况

**Comment by laolizhennui** [comment]
> 使用 `xlings install vscode` 能显示已经被安装吗? 还是提示重新安装, 可以在powershell 和 cmd 上都试一下 看看情况

PowerShell：
PowerShell 7.5.0-preview.5

   A new PowerShell preview release is available: v7.5.0-rc.1
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.5.0-rc.1

PS C:\Users\Administrator> xlings install vscode

--- info

name: vscode
homepage: https://code.visualstudio.com
author: https://github.com/microsoft/vscode/graphs/contributors
licenses: MIT
github: https://github.com/microsoft/vscode
docs: https://code.visualstudio.com/docs

        Visual Studio Code

[xlings]: install vscode? (y/n)

cmd：
C:\Users\Administrator>xlings install vscode

--- info

name: vscode
homepage: https://code.visualstudio.com
author: https://github.com/microsoft/vscode/graphs/contributors
licenses: MIT
github: https://github.com/microsoft/vscode
docs: https://code.visualstudio.com/docs

        Visual Studio Code

[xlings]: install vscode? (y/n)

**Comment by laolizhennui** [comment]
系统环境变量：
![image](https://github.com/user-attachments/assets/487afbbb-fe64-49c7-9cb1-c7eb4b250c5a)
用户环境变量：
![image](https://github.com/user-attachments/assets/b35375ba-c29e-4ae4-8696-205c52e7e7ec)

**Comment by Sunrisepeak** [comment]
@laolizhennui 这个问题可能是administrator用户下引起的。这个我排查一下问题

**Comment by Sunrisepeak** [comment]
应该确实和admin账户有关系, vscode 对普通账户和admin账户有区别, 我看一下这个问题怎么解决

![image](https://github.com/user-attachments/assets/7824cd83-18c9-4a07-8e56-10f61048d6c2)

**Comment by Sunrisepeak** [comment]
@laolizhennui 问题已修复可以重新安装xlings进行测试

![image](https://github.com/user-attachments/assets/971cc6d7-fd31-4e00-a14d-c2b31d74498a)

重新安装后可以使用

```bash
xlings install vscode
```

或 短命令(别名)

```bash
xinstall vscode
```

进行验证
