### ISSUE TITLE
[features]:安装Rust使用GNU工具链

### ISSUE THREAD

**Issue by laolizhennui** [d2learn/xlings#30]
### Features Describe | 功能描述
安装Rust编程语言时可以选择使用GNU工具链

###  Maybe Solutions | 可能的实现方案 - (if you are developer)
在用户想要安装Rust时，可以选择使用MSVC工具链或者使用GNU工具链

**Comment by Sunrisepeak** [comment]
@laolizhennui 现在已经支持, 可以用最新版本进行尝试

![image](https://github.com/user-attachments/assets/a0258ae0-7ca9-452c-8d46-669a77c651c1)

**Comment by laolizhennui** [comment]
666
