### ISSUE TITLE
"xlings" isn't recognized as a name of a cmdlet.

### ISSUE THREAD

**Issue by lvyuemeng** [d2learn/xlings#33]
### Background | 背景

OS: windows11

### Describe | 问题描述

After install it by `Invoke-Expression (Invoke-Webrequest 'https://d2learn.org/xlings-install.ps1.txt' -UseBasicParsing).Content`, refresh powershell, type "xlings", shows: 
> "xlings: The term 'xlings' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

### Desktop | 环境

OS: windows11

### Additional context | 额外补充

After install it without refreshing, I could use "xlings"

**Comment by Sunrisepeak** [comment]
Q1: is it only not found in current powershell window?  - sitll is a issue
Q2: can 'xlings' recognized by reopen a new cmd or powershell?
Q3: Is your username is Administrator?

**Comment by Sunrisepeak** [comment]
https://github.com/d2learn/xlings/blob/ed77bc8727d0308d515477010b6b60032b774f70/tools/other/quick_install.ps1#L155

**Comment by lvyuemeng** [comment]
> Q1: is it only not found in current powershell window? - sitll is a issue Q2: can 'xlings' recognized by reopen a new cmd or powershell? Q3: Is your username is Administrator?

A1: If I reopen powershell, it can't recognize `xlings`, the scope of `xlings` only works on powershell window I install `xlings`
A2: as above.
A3: Yes.

**Comment by lvyuemeng** [comment]
I don't see env modification when I check it. Here it use
> Tab completion service
>   => installing shell integration to C:\Users\nostalgia\OneDrive\文档\PowerShell\profile.ps1 .. ok
> Tab completion installed
> [xlings]: set xlings to PATH
and create a profile.ps1 link to the script of `xlings`, bu it doesn't seem to work for me.

**Comment by Sunrisepeak** [comment]
@lvyuemeng
maybe exist some issue in install procedure
can you install xlings again? then paste all install's log to 'To Reproduce | 复现步骤'

**Comment by lvyuemeng** [comment]
> repo:  https://github.com/d2learn/xlings
> forum: https://forum.d2learn.org                                                                                                                                                                                                                                  ---                                                                                                                              Testing network...                                                                                                               WARNING: Unable to ping github.com
> WARNING: Unable to ping gitee.com
> Latency for github.com : 999999 ms
> Latency for gitee.com : 999999 ms
> [xlings]: start detect environment and try to auto config...
> [xlings]: start install xmake...   
> 
>                       _
>     __  ___ __  __  __ _| | ______
>     \ \/ / |  \/  |/ _  | |/ / __ \
>      >  <  | \__/ | /_| |   <  ___/
>     /_/\_\_|_|  |_|\__ \|_|\_\____| getter
> 
> 
> Start downloading https://github.com/xmake-io/xmake/releases/download/v2.9.6/xmake-master.win64.exe ..
> Start installation... Hope your antivirus doesn't trouble
> Install to C:\Users\nostalgia\xmake
> Adding to PATH... almost done
> xmake v2.9.6+master.2f1213a70, A cross-platform build utility based on Lua
> Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
>                          _
>     __  ___ __  __  __ _| | ______
>     \ \/ / |  \/  |/ _  | |/ / __ \
>      >  <  | \__/ | /_| |   <  ___/
>     /_/\_\_|_|  |_|\__ \|_|\_\____|
>                          by ruki, xmake.io
> 
>     👉  Manual: https://xmake.io/#/getting_started
>     🙏  Donate: https://xmake.io/#/sponsor
> 
> Tab completion service
>   => installing shell integration to C:\Users\nostalgia\OneDrive\文档\PowerShell\profile.ps1 .. ok
> Tab completion installed
> [xlings]: set xlings to PATH
> 
> WARNING: The data being saved is truncated to 1024 characters.
> 
> SUCCESS: Specified value was saved.
> [xlings]: xlings uninstalled(C:/Users/Public/xlings) - ok
> [xlings]: install xlings to C:/Users/Public/xlings
> [xlings]: add bin to linux's .bashrc or windows's path env
> [xlings]: xlings installed
> 
>     run xlings help get more information
> 
> removing directory: F:\Stratum\TEMP\xlings (tmpfiles)
> xlings has been successfully installed.

**Comment by lvyuemeng** [comment]
I try to solely install xmake, and it works. So I guess there's a deficit installation in xlings

**Comment by Sunrisepeak** [comment]
install-script updated already. you can re-install to verify.

```bash
xlings uninstall
Invoke-Expression (Invoke-Webrequest 'https://d2learn.org/xlings-install.ps1.txt' -UseBasicParsing).Content
```

https://github.com/d2learn/xlings/blob/06274b10ef09e13c1cec6fe70324cd65f5304940/tools/other/quick_install.ps1#L154-L164

**Comment by lvyuemeng** [comment]
> install-script updated already. you can re-install to verify.
> 
> ```shell
> xlings uninstall
> Invoke-Expression (Invoke-Webrequest 'https://d2learn.org/xlings-install.ps1.txt' -UseBasicParsing).Content
> ```
> 
> https://github.com/d2learn/xlings/blob/06274b10ef09e13c1cec6fe70324cd65f5304940/tools/other/quick_install.ps1#L154-L164

It works now, thanks!
