### ISSUE TITLE
[features]: 添加对mingw的支持 | xlings checker/dslings 练习代码自动检测

### ISSUE THREAD

**Issue by luyuduan** [d2learn/xlings#34]
### Features Describe | 功能描述
windows安装cpp/c++/c的话，添加对mingw编译套件的支持

###  Usage Scenario | 需求背景/使用场景
不想安装MSVC或者已经安装了其他编译套件

###  Maybe Solutions | 可能的实现方案 - (if you are developer)
1. 安装时支持编译套件选择，或者选择已安装的路径，配置默认的编译套件路径
2. 安装后再配置或修改编译套件，比如我已经装了mingw，xmake就支持这样设置**工程级**的编译套件路径
```
Command options (MingW Configuration):
        --mingw=MINGW                      The MingW SDK Directory
```

### Additional context | 额外补充
所以我的环境总是卡在安装环境上

**Comment by Sunrisepeak** [comment]
你是指你在用`xlings run`去运行c/c++程序的时候使用mingw吗

**Comment by luyuduan** [comment]
xlings dslings
或者
xlings install c 
都会有下面这一步
```
checking for Microsoft Visual Studio (x64) version ... no
Check MSVC Tools...
[xlings]: install c? (y/n)
```
我选n就再次一样的询问，还是要求我安装MSVC 。

目前我只想试用下xlings 的面向编译器开发的示例，都没有办法

**Comment by luyuduan** [comment]
目前这样凑合
![image](https://github.com/user-attachments/assets/f936ca07-5718-4e4a-9115-3c7471845ba6)

**Comment by Sunrisepeak** [comment]
https://github.com/d2learn/xlings/commit/0db9f9d148464b313948f4a1b6eab63b0de7c01a

对于练习代码自动检测中, 增加了mingw的支持。可以直接从源码安装最新版本然后再使用`xlings dslings`运行d2ds的检测

**更新到最新版本**

```bash
git clone https://github.com/d2learn/xlings.git
cd xlings
tools/install.win.bat
```

**运行d2ds的代码检测**

```bash
cd yourPath/d2ds
xlings dslings
```

---

> 注: 修改会尽快同步到, 一键安装命令的服务仓库

**Comment by luyuduan** [comment]
我把我的d2ds修改删除后，也不会让我安装MSCV了。
问题解决
