### ISSUE TITLE
[features]: xinstall rename is_installed to version_of

### ISSUE THREAD

**Issue by MoYingJi** [d2learn/xlings#44]
### Features Describe | 功能描述
如题 在包管理器的脚本中 将 is_installed 改为 version_of

###  Usage Scenario | 需求背景/使用场景
现在 包管理器脚本中暂时没有一个查询某软件包版本的方法
个人认为 可以将此方法和 is_installed 结合为 version_of 并在未安装时返回 nil

###  Maybe Solutions | 可能的实现方案 - (if you are developer)
pacman.lua
```lua
function version_of(package_name)
    local r = utils.try_run("pacman -Q " .. package_name)
    if not r then return nil end
    local ok = r.ok
    if not ok or ok == "" then return nil end
    return ok:split(' ')[2]:split('-')[1]
end
```

### Additional context | 额外补充
应该仅为版本号或特殊值而不包含其他？
（如 arch linux 的发行号）

**Comment by Sunrisepeak** [comment]
已经引入对应版本号识别 (通过installed中去匹配版本号)

https://github.com/d2learn/xim-pkgindex/blob/bb727e033981be5bc0d3f39d702ba7a4cb9a9c8a/pkgs/m/mdbook.lua#L52

![image](https://github.com/user-attachments/assets/2fb7a49a-4b7c-4c11-8d42-7b06e485b8b1)
